import { Timestamp } from "firebase/firestore";

export default {
  hashtag_regex: /(#\S+?)(?=#|\s|$)/g,
  thumb_def_size: 640,
  thumb_def_type: "image/jpeg",
  thumb_def_quality: 0.8,
  testData: [
    {
      id: "needs_0",
      title: "畑を守りたい",
      type: "needs",
      desc: "スライムの被害から農作物を守り、安定した収穫を得たい。",
      star: 2,
    },
    {
      id: "needs_1",
      title: "スライムを安全に排除したい",
      type: "needs",
      desc: "スライムを刺激して分裂させたりせず、安全な方法で退治したい。",
      star: 3,
    },
    {
      id: "needs_2",
      title: "作業の負担を減らしたい",
      type: "needs",
      desc: "毎晩見回りをする労力や、荒らされた畑を修復する手間をなくしたい。",
      star: 1,
    },
    {
      id: "needs_3",
      title: "スライムを資源として活用したい",
      type: "needs",
      desc: "ただの害獣ではなく、薬や肥料など、何かに役立てたい。",
      star: 3,
    },
    {
      id: "needs_4",
      title: "安心して眠りたい",
      type: "needs",
      desc: "夜中に畑が荒らされる心配をせず、ゆっくり休みたい。",
      star: 2,
    },
    {
      id: "seeds_0",
      title: "岩塩の結晶",
      type: "seeds",
      desc: "村の近くの洞窟で採れる、スライムに触れると一時的に固まらせる効果がある結晶。",
      star: 2,
    },
    {
      id: "seeds_1",
      title: "特定の植物",
      type: "seeds",
      desc: "畑の近くに自生している、スライムが嫌う強い匂いを発する植物。",
      star: 1,
    },
    {
      id: "seeds_2",
      title: "炎の魔法",
      type: "seeds",
      desc: "勇者が使える初級魔法。スライムの水分を蒸発させる効果がある。",
      star: 2,
    },
    {
      id: "seeds_3",
      title: "古い錬金術の知識",
      type: "seeds",
      desc: "村の図書館に眠る古文書に記された、スライムの体液を中和するレシピ。",
      star: 3,
    },
    {
      id: "seeds_4",
      title: "スライムの天敵",
      type: "seeds",
      desc: "スライムを捕食する習性を持つ、硬い甲羅を持つ巨大なカエル。",
      star: 2,
    },
    {
      id: "persona_0",
      title: "勇者リオン",
      type: "persona",
      desc: "正義感が強く、困っている人を助けることを使命とする。剣術と初歩的な魔法が使える。",
      star: 2,
    },
    {
      id: "persona_1",
      title: "農夫エルム",
      type: "persona",
      desc: "代々続く農家の青年。力仕事は得意だが、魔法や戦闘の知識はない。家族の生活を守ることに必死。",
      star: 1,
    },
    {
      id: "persona_2",
      title: "行商人ベラ",
      type: "persona",
      desc: "スライムの出る危険な道を往来する商人。戦闘を避け、安全かつ効率的に移動することを優先する。",
      star: 3,
    },
    {
      id: "persona_3",
      title: "賢者ゼノン",
      type: "persona",
      desc: "魔法や生態系に詳しい学者。スライムの生態を研究し、根本的な解決策を探求している。",
      star: 1,
    },
    {
      id: "persona_4",
      title: "村長ボルドー",
      type: "persona",
      desc: "村のリーダー。住民の安全と村の経済を安定させることが使命。費用対効果を重視する。",
      star: 1,
    },
    {
      id: "context_0",
      title: "スライムが畑を荒らす",
      type: "context",
      desc: "スライムが夜中に出没し、畑をめちゃくちゃにしてしまう。",
      star: 2,
    },
    {
      id: "context_1",
      title: "物理攻撃が効きにくい",
      type: "context",
      desc: "スライムは弾力のある体で、剣や槍などの物理攻撃をほとんど弾いてしまう。",
      star: 3,
    },
    {
      id: "context_2",
      title: "環境への悪影響",
      type: "context",
      desc: "むやみにスライムを倒すと、分解された体液が土壌を汚染し、作物が育たなくなる。",
      star: 3,
    },
    {
      id: "context_3",
      title: "水路が汚染されている",
      type: "context",
      desc: "スライムの体液で村の水路が汚染され、飲料水として使えなくなってきている。",
      star: 2,
    },
    {
      id: "context_4",
      title: "スライムの個体数が増加している",
      type: "context",
      desc: "数年前からスライムの個体数が異常に増え、対処が困難になっている。",
      star: 2,
    },
    {
      id: "challenge_0",
      title: "農夫エルムは夜間の畑のスライムに悩んでいる",
      type: "challenge",
      desc: "夜間に活動するスライムによって畑の作物が荒らされ、エルムは毎晩見回りを強いられている。",
      star: 1,
    },
    {
      id: "challenge_1",
      title: "物理攻撃が効かないスライムの排除が困難",
      type: "challenge",
      desc: "剣や槍といった一般的な武器が通じないため、スライムを効率的に倒す方法がない。",
      star: 1,
    },
    {
      id: "challenge_2",
      title: "スライムの体液が環境を破壊する",
      type: "challenge",
      desc: "スライムを倒すと土壌が汚染され、畑が使えなくなるという新たな問題が発生する。",
      star: 2,
    },
    {
      id: "challenge_3",
      title: "スライムの発生源が不明",
      type: "challenge",
      desc: "どこからスライムが現れるのか、なぜ個体数が増えたのかが分からず、根本的な解決策が立てられない。",
      star: 2,
    },
    {
      id: "challenge_4",
      title: "村全体で統一された対策がない",
      type: "challenge",
      desc: "各農夫がバラバラに対処しているため、村全体のスライム問題を解決できていない。",
      star: 3,
    },
    {
      id: "idea_0",
      title: "岩塩バリアの設置",
      type: "idea",
      desc: "畑の周囲に岩塩のブロックを並べ、スライムが嫌がる結界を作る。",
      star: 2,
    },
    {
      id: "idea_1",
      title: "天敵誘引作戦",
      type: "idea",
      desc: "スライムを食べるカエルを畑に放ち、自然の力で個体数を減らす。",
      star: 2,
    },
    {
      id: "idea_2",
      title: "塩水スプリンクラー",
      type: "idea",
      desc: "岩塩を溶かした水を畑に散布する装置を作り、夜間に自動でスライムを無力化する。",
      star: 3,
    },
    {
      id: "idea_3",
      title: "スライム結晶化魔法",
      type: "idea",
      desc: "スライムを倒すのではなく、無害な岩塩の結晶に変える魔法を開発する。",
      star: 2,
    },
    {
      id: "idea_4",
      title: "スライム忌避剤の開発",
      type: "idea",
      desc: "スライムが嫌う植物を元に、畑の土壌に混ぜることでスライムを寄せ付けない忌避剤を作る。",
      star: 2,
    },
  ],
  menu: {
    ITEM: "item",
    ENCHANT: "enchant",
    MESSAGE_LOG: "message_log",
    OPTION: "option",
  },
  action: {
    type: {
      DEBUG_RANDOM_FRAGMENTS: "debug_random_fragments",
      DEBUG_COMPLETE_FRAGMENTS: "debug_complete_fragments",
      INIT_GAME: "init_game",
      NEXT_DAY: "next_day",
      CHANGE_PROGRESS: "change_progress",
      SELECT_ITEM: "select_item",
      GET_FRAGMENT: "get_fragment",
      ADD_FRAGMENT: "add_fragment",
      SET_FRAGMENT: "set_fragment",
      SET_FRAGMENTS: "set_fragments",
      REMOVE_FRAGMENT: "remove_fragment",
      RESET_FRAGMENTS: "reset_fragments",
      ACTIVE_FRAGMENT: "active_fragment",
      DEACTIVE_FRAGMENT: "deactive_fragment",
      ACTIVE_FRAGMENT_TYPE: "active_fragment_type",
      RESET_RESULTS: "reset_results",
      ADD_MESSAGE: "add_message",
      SEND_MESSAGE: "send_message",
      ENCHANT_MERGE: "enchant_merge",
      SEND_MESSAGE: "send_message",
      SET_SLOT: "set_slot",
      SET_SLOTS: "set_slots",
      REMOVE_SLOT: "remove_slot",
      RESET_SLOT: "reset_slot",
      SELECT_SLOT: "select_slot",
      UNSELECT_SLOT: "unselect_slot",
      ENCHANT_SCAMPER: {
        S: "enchant_scamper_s",
        C: "enchant_scamper_c",
        A: "enchant_scamper_a",
        M: "enchant_scamper_m",
        P: "enchant_scamper_p",
        E: "enchant_scamper_e",
        R: "enchant_scamper_r",
      },
    },
  },
  message: {
    type: {
      TALK: "talk",
      USER_ACTION: "user_action",
      FREE_ACTION: "free_action",
      GET_FRAGMENTS: "get_fragments",
      ENCHANT_MERGE: "enchant_merge",
      ENCHANT_SCAMPER: "enchant_scamper",
    },
    role: {
      SYSTEM: "system",
      USER: "user",
    }
  },
  status: {
    SUCCESS: "success",
    FAILED: "failed",
  },
  scamper: {
    type: {
      S: "substitute",
      C: "combine",
      A: "adapt",
      M: "modify",
      P: "put_to_other",
      E: "eliminate",
      R: "rearrange",
    },
    info: {
      substitute: {
        name: "代用する",
        desc: "何か別のものに置き換えられないか？",
      },
      combine: {
        name: "組み合わせる",
        desc: "複数の要素を組み合わせられないか？",
      },
      adapt: {
        name: "適応させる",
        desc: "ほかの要素から何か適用できないか？",
      },
      modify: {
        name: "修正する",
        desc: "形や大きさを変えられないか？",
      },
      put_to_other: {
        name: "転用する",
        desc: "現在の用途とは別の目的で使えないか？",
      },
      eliminate: {
        name: "取り除く",
        desc: "何かを削除または簡略化できないか？",
      },
      rearrange: {
        name: "再編成する",
        desc: "順番を逆もしくは入れ替えられないか？",
      },
    },
  },
  fragment: {
    type: {
      ALL: "all",
      NEEDS: "needs",
      SEEDS: "seeds",
      PERSONA: "persona",
      CONTEXT: "context",
      CHALLENGE: "challenge",
      IDEA: "idea",
    },
    info: {
      all: {
        name: "ALL",
        desc: "ALL",
      },
      needs: {
        name: "ニーズ",
        desc: "ユーザーが抱える課題や欲求",
      },
      seeds: {
        name: "シーズ",
        desc: "ユーザーの持つ技術や知識、資源",
      },
      persona: {
        name: "ペルソナ",
        desc: "具体化した仮想ユーザー像",
      },
      context: {
        name: "コンテクスト",
        desc: "ユーザーの具体的な状況や背景",
      },
      challenge: {
        name: "チャレンジ",
        desc: "ニーズとシーズ、ペルソナ、コンテキストが結合して生まれる解決すべき問題",
      },
      idea: {
        name: "アイデア",
        desc: "チャレンジを解決できるもの",
      },
    },
  },
};
