export default {
    logo: require("./logo_02.svg").default,
    logo_w: require("./logo.svg").default,
    like_yes: require("./Picture27.svg").default,
    like_no: require("./Picture26.svg").default,
    comment: require("./Picture25.svg").default,
    chat_send_yes: require("./Picture30.svg").default,
    chat_send_no: require("./Picture31.svg").default,
    thumb_default: require("./thumb_default.png"),
    test: require("./Test_640x640.png"),
    chara_01: require("./chara_01.png"),
    chara_02: require("./chara_02.png"),
    banner_01: require("./banner_01.png"),
    banner_02: require("./banner_02.png"),
    banner_03: require("./banner_03.png"),
}